# GitHub Action Workflow

name: Build Examples for ESP32

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build Examples for ESP32
  build-esp32:
    name: build examples on ESP32
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Run Arduino Compiler
      # see https://github.com/arduino/compile-sketches
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          verbose: true
          platforms: |
            # Install ESP32 platform via Boards Manager
            - name: "esp32:esp32"
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              # version: 2.0.4 doesn't work with CLI caused by issue https://github.com/espressif/arduino-esp32/pull/7060
              version: 2.0.2
          fqbn: esp32:esp32:esp32
          libraries: |
            - source-path: ./
          sketch-paths: |
            - 'examples/SerialRadio'
            - 'examples/ScanRadio'
